### ISSUE TITLE
logoutボタンについて

### ISSUE THREAD

**Issue by rujiie** [shin-hiroshi/Assignment2#3]
btnLogoutはloginボタンが押された時に作成していますが
ここで作成する必要ないと思います。
下記の4つも同じです。
    private var lblLastLogin: UILabel!
    private var btnLogin: UIButton!
    private var btnLogout: UIButton!
    private var btnSettings: UIButton!
これらはletにできます。
下記のように。
> private let lblLastLogin: UILabel = UILabel()

**Comment by shin-hiroshi** [comment]
現在のロジックに、下記の難点があります：
１、loginボタンを押下する際、btnLogoutの存在は判断必要
２、letに変更したら、create関数が利用出来なくなる
３、create関数にstyleの設定があるので、無視できない

**Comment by rujiie** [comment]
１、loginボタンを押下する際、btnLogoutの存在は判断必要
ログインボタン押下時になぜbtnLogoutの存在チェックが必要なのでしょうか。
ログインボタンタップ時はログインボタン、ログアウトボタンのisHiddenをセットするだけで
良いのではないですか。
２、letに変更したら、create関数が利用出来なくなる
３、create関数にstyleの設定があるので、無視できない
letで作成し、スタイルやタップイベントなどは後でセットすればいいだけだと思います。

**Comment by matsumoto777** [comment]
@shin-hiroshi 
ログアウトボタンも最初に作るべき。
最初に作ればnilチェックが不要になります。
If it is made first, nil check is unnecessary.

**Comment by shin-hiroshi** [comment]
ロジックを変更いたしました。
