### ISSUE TITLE
setButton, setLabelのメソッド名について

### ISSUE THREAD

**Issue by matsumoto777** [shin-hiroshi/Assignment2#5]
```
        self.setButton(button: btnLogin, title: "ログイン")
```

上記のソースを見たとき、
selfにbtnLoginをセットしているような印象を受けます。

setButtonではなく、applyBtnStyle等、メソッド名を工夫した方が読みやすい。
でも、一番良いのは、メソッドにせず展開してしまうことだと思います。

**Comment by shin-hiroshi** [comment]
set関数を削除して、設定をinitに展開いたしました
