### ISSUE TITLE
レイアウトのロジック

### ISSUE THREAD

**Issue by matsumoto777** [shin-hiroshi/Assignment2#6]
layoutSubviews内のレイアウトロジックについて。

平間さんのロジックの方が読みやすくて、かつ、汎用性があります。
比べてみて。
https://github.com/YuukiHirama/Task2/blob/master/Task2/Task2/CustomView.swift

**Comment by shin-hiroshi** [comment]
https://github.com/shin-hiroshi/Assignment2/issues/5 に更新いたしました

**Comment by matsumoto777** [comment]
> #5 に更新いたしました

??
どういう意味かわからないです。

**Comment by shin-hiroshi** [comment]
setメソッドの替わりに、展開の設定を利用しております。

**Comment by matsumoto777** [comment]
本来はコメントになっているコードを削除しておいてほしいですが、今回はOKとします。

ちなみにfor文にできるのはラベル以外です。
