### ISSUE TITLE
ViewControllerのviewDidLayoutSubviews

### ISSUE THREAD

**Issue by rujiie** [shin-hiroshi/Assignment2#7]
superのviewDidLayoutSubviewsを呼んでください。
また、mainView.layoutSubviews()を行っていますが
layoutSubviewsは直接呼ぶものではありません。
mainViewのframeをセットすることで勝手に呼ばれます。

**Comment by shin-hiroshi** [comment]
https://github.com/shin-hiroshi/Assignment2/issues/4 に更新いたしました

**Comment by shin-hiroshi** [comment]
mainView.layoutSubviews() 削除済

**Comment by shin-hiroshi** [comment]
super.viewDidLayoutSubviews()呼出
