### ISSUE TITLE
ViewControllerのmainView

### ISSUE THREAD

**Issue by rujiie** [shin-hiroshi/Assignment2#8]
ViewControllerのmainViewもletにすべきです。
また、mainView作成時にframeで位置、サイズなどを指定していますが
viewDidLayoutSubviewsで再セットされるので不要です。
viewDidLayoutSubviewsでwidthだけセットしていますが
heightもセットすべきです。

**Comment by shin-hiroshi** [comment]
一度試してみたのですが、
viewDidLayoutSubviewsにyの位置を指定しなければ、画面が正確的に表示できません。
portraitの画面にheightを設定しなければ、labelの文字は完全的に表示できないですけど、landscapeでは問題ありません。

**Comment by rujiie** [comment]
yの位置ではなくheightです。
mainviewの位置、サイズはviewDidLoad ではなく
viewDidLayoutSubviewsで行うべきです。
